- *PoC* Proof of Concept
- *iOS* iPhone Operating System
- *App* Application
- *UML* Unified Modeling Language
- *CRDT* Conflict-free Replicated Data Type
- *UX* User Experience
- *UI* User Interface
- *SVG* Scalable Vector Graphics
- *JSON* JavaScript Object Notation
- *REST* Representational State Transfer
- *API* Application Programming Interface
- *FR* Functional Requirement
- *QA* Quality Attribute
- *CRUD* Create Read Update Delete